<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OmniEMU.Audio\OmniEMU.Audio.csproj" />
    <ProjectReference Include="..\OmniEMU.Common\OmniEMU.Common.csproj" />
    <ProjectReference Include="..\OmniEMU.Horizon.Common\OmniEMU.Horizon.Common.csproj" />
    <ProjectReference Include="..\OmniEMU.Horizon.Generators\OmniEMU.Horizon.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\OmniEMU.Memory\OmniEMU.Memory.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Concentus" />
    <PackageReference Include="LibHac" />
  </ItemGroup>
</Project>
