<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>OmniEMU.BugTester</AssemblyName>
    <RootNamespace>OmniEMU.BugTester</RootNamespace>
    <Version>0.1.0</Version>
    <PublishSingleFile>true</PublishSingleFile>
  </PropertyGroup>
</Project>
