using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace OmniEMU.BugTester;

public static class ReportWriter
{
    public static (string Json, string Markdown) Write(DiagnosticReport report, string outputDirectory)
    {
        Directory.CreateDirectory(outputDirectory);
        string jsonPath = Path.Combine(outputDirectory, "omniemu-bug-report.json");
        string markdownPath = Path.Combine(outputDirectory, "omniemu-bug-report.md");

        JsonSerializerOptions options = new()
        {
            WriteIndented = true,
            Converters = { new JsonStringEnumConverter() },
        };
        File.WriteAllText(jsonPath, JsonSerializer.Serialize(report, options));
        File.WriteAllText(markdownPath, ToMarkdown(report));
        return (Path.GetFullPath(jsonPath), Path.GetFullPath(markdownPath));
    }

    private static string ToMarkdown(DiagnosticReport report)
    {
        StringBuilder text = new();
        text.AppendLine("# OmniEMU BugTester report");
        text.AppendLine();
        text.AppendLine($"- **Generated:** {report.GeneratedAtUtc:O}");
        text.AppendLine($"- **Operating system:** {Escape(report.OperatingSystem)}");
        text.AppendLine($"- **Architecture:** {report.Architecture}");
        text.AppendLine($"- **Runtime:** {Escape(report.Framework)}");
        text.AppendLine($"- **App data:** `{EscapeCode(report.AppDataPath)}`");
        if (report.SourcePath is not null)
        {
            text.AppendLine($"- **Source:** `{EscapeCode(report.SourcePath)}`");
        }
        text.AppendLine($"- **Summary:** {report.Errors} errors · {report.Warnings} warnings · {report.Passed} passed checks");
        text.AppendLine();
        text.AppendLine("> This report does not include encryption-key, firmware, game, save, or account contents. Review paths and log messages for personal information before posting publicly.");

        foreach (Severity severity in new[] { Severity.Error, Severity.Warning, Severity.Info, Severity.Pass })
        {
            Finding[] findings = report.Findings.Where(f => f.Severity == severity).ToArray();
            if (findings.Length == 0) continue;
            text.AppendLine();
            text.AppendLine($"## {Icon(severity)} {severity} ({findings.Length})");
            foreach (Finding finding in findings)
            {
                text.AppendLine();
                text.AppendLine($"### `{finding.Code}` {Escape(finding.Title)}");
                text.AppendLine();
                text.AppendLine($"- **Category:** {Escape(finding.Category)}");
                if (finding.Occurrences > 1) text.AppendLine($"- **Occurrences:** {finding.Occurrences}");
                if (finding.Path is not null)
                {
                    string location = finding.Line is null ? finding.Path : $"{finding.Path}:{finding.Line}";
                    text.AppendLine($"- **Location:** `{EscapeCode(location)}`");
                }
                text.AppendLine($"- **Detail:** {Escape(finding.Detail)}");
                if (finding.Remediation is not null)
                {
                    text.AppendLine($"- **Suggested action:** {Escape(finding.Remediation)}");
                }
            }
        }
        text.AppendLine();
        text.AppendLine("---");
        text.AppendLine("Generated by OmniEMU BugTester 0.1.0 · Created and maintained by OmniNodeCo.");
        return text.ToString();
    }

    private static string Icon(Severity severity) => severity switch
    {
        Severity.Error => "❌",
        Severity.Warning => "⚠️",
        Severity.Info => "ℹ️",
        _ => "✅",
    };

    private static string Escape(string value) => value.Replace("|", "\\|").Replace("\r", " ").Replace("\n", " ");
    private static string EscapeCode(string value) => value.Replace("`", "'");
}
